name: Generate GitHub Trophy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  trophy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: gAurav-0x07
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push trophy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git clone https://github.com/gAurav-0x07/gAurav-0x07.git repo
          cd repo

          mkdir -p trophy-output
          cp ../trophy.svg trophy-output/trophy.svg

          git add trophy-output/trophy.svg
          git commit -m "Update GitHub trophy" || exit 0
          git push
